### ISSUE TITLE
"stdlib.h" not found in stdlib_checked.h

### ISSUE THREAD

**Issue by jiezhoucs** [checkedc/checkedc-clang#1185] opened 2021-09-25 00:18 UTC
I just compiled `CheckedC-Clang-12.0.1-rel3` (with the same tagged [checkedc](https://github.com/microsoft/checkedc)) on MacOS 11.6. There were no compilation problems, but when using the compiler to compile a simple hello world program, I got an error

```
/path_of_my_build_dir/lib/clang/12.0.1/include/stdlib_checked.h:14:15: fatal error: 'stdlib.h' file not found
#include_next <stdlib.h>
```

I checked the `/path_of_my_build_dir/lib/clang/12.0.1/include` directory, and the `stdlib.h` defined in the checkedc repo was installed there. Either deleting the `#include_next <stdlib.h>` line in `stdlib_checked.h` or changing `#include_next` to `#include` would remove the error, but I'm not sure if that would break anything.

**Comment by mattmccutchen-cci** [comment] 2021-09-28 23:57
The include path is supposed to be set up so that the header directory for the system C library comes after Clang's built-in header directory, so `#include_next <stdlib.h>` should load the system header file.  I guess that didn't work properly in your build, or maybe the system C library headers are not installed properly on your system; that kind of thing often requires extra steps on Mac OS.  Changing the `#include_next <stdlib.h>` to `#include <stdlib.h>` (to load the Checked C wrapper header) or deleting it altogether may make the include error go away but may ultimately leave your program without system C library declarations that it needs for subsequent calls to anything in `stdlib.h` to actually execute correctly, so it's not a good solution.

The problem most likely isn't specific to Checked C.  I suggest you first try to build upstream Clang (which, unlike the Checked C fork, doesn't have a `stdlib.h` file of its own), fiddle with it until you can successfully compile a plain C program that includes `stdlib.h`, and then try to replicate the same configuration with the Checked C fork of Clang.  Note that you can add `-v` to the compiler command line to see the built-in include path.

**Comment by jzhou76** [comment] 2021-09-29 00:50
> The include path is supposed to be set up so that the header directory for the system C library comes after Clang's built-in header directory, so `#include_next <stdlib.h>` should load the system header file. I guess that didn't work properly in your build, or maybe the system C library headers are not installed properly on your system; that kind of thing often requires extra steps on Mac OS. Changing the `#include_next <stdlib.h>` to `#include <stdlib.h>` (to load the Checked C wrapper header) or deleting it altogether may make the include error go away but may ultimately leave your program without system C library declarations that it needs for subsequent calls to anything in `stdlib.h` to actually execute correctly, so it's not a good solution.
> 
> The problem most likely isn't specific to Checked C. I suggest you first try to build upstream Clang (which, unlike the Checked C fork, doesn't have a `stdlib.h` file of its own), fiddle with it until you can successfully compile a plain C program that includes `stdlib.h`, and then try to replicate the same configuration with the Checked C fork of Clang. Note that you can add `-v` to the compiler command line to see the built-in include path.

I agree that it might have something to do with libc header files installed on MacOS. It is a pretty common problem on MacOS, especially every time after a system upgrade.

For this case, I just tried compiling with `-v` and it shows `/usr/local/include` is in the search paths for `#include`, and I confirmed that both `stdio.h` and `stdlib.h` are indeed installed in `/usr/local/include`. However, it still reports the `'stdlib.h' file not found` error for `#include_next <stdlib.h>`.

**Comment by mattmccutchen-cci** [comment] 2021-09-29 01:56
What is the full include path shown by `-v`?  If your system libc headers are in `/usr/local/include`, but that directory is before `/path_of_my_build_dir/lib/clang/12.0.1/include` on the include path, then the `#include_next` will not work.  You want the system headers to be after the Clang built-in headers, whether or not you are using the Checked C fork of Clang, since some built-in headers of upstream Clang also use `#include_next`.  You may be able to achieve that via something like `-nostdlibinc -idirafter /usr/local/include`.  But really the build configuration should be fixed so you don't have to pass extra compiler options on every run.  I can't provide help specific to Mac OS, but you could look at [these instructions](https://github.com/correctcomputation/checkedc-clang/blob/main/clang/docs/checkedc/3C/INSTALL.md#mac-os-x) or other resources on the web.

**Comment by dtarditi** [comment] 2024-09-01 17:59
I think you need to set the SDKROOT environment variable so that the Checked C clang compiler knows where to find the Apple SDK that defines stdlib.h.   You can find the location of the SDK that Xcode is currently using with `xcrun -show-sdk-path`.  

On my current system, this command shows the result `/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk`.  With SDKROOT set to that, the Mac [release](https://github.com/checkedc/checkedc-llvm-project/releases/tag/CheckedC-Clang-12.0.2) of the Checked C clang compiler compiles `hello-world.c` just fine.

**Closed by dtarditi** 2024-09-01 17:59 UTC
