### ISSUE TITLE
Extend Benchmark Automation Code to support performance measurements.

### ISSUE THREAD

**Issue by lenary** [checkedc/checkedc-clang#238] opened 2017-03-29 19:12 UTC
I've found that the test suite when run with CMake gives far better error messages (such as compile errors) than when run with makefiles. 

We have an outstanding pull request to make the CMake build work (adding the include directory). After that is merged it would be good to use the CMake system, if only so we can better diagnose build failures in the benchmarks. 

https://github.com/lenary/checkedc-travis-builder/blob/master/benchmark.sh#L13-L22 is a simple script that will run the Cmake test suite. This requires knowing where CMake is (or having it on the path). There are extra useful arguments:
- `--only-test <DIR>` works just like the nt tests
- `--exec-multisample=<n>` for executing each benchmark more than once (in the nt suite, this is called `--multisample`)

**Comment by dtarditi** [comment] 2017-06-20 22:20
It turns out things are more complicated than this:
- The LNT nightly regression tests use the make-based system.   it is fairly straightforward to debug and use.
- The LNT performance measurements use the cmake-based system.   These depend on things like link-time optimization.   That in turn depends on a variety of things, such as having additional tools built that can plug into the GCC linker support for LTO, as well as the right version of the GCC linker.   It would be quite difficult to debug correctness regressions using the LTO tool chain.

So we don't want to convert the existing benchmark automation code to use cmake: the existing system is mainly meant to detect to compiler regressions/problems.  We want to extend it instead to support performance measurements using cmake.   We'll need to make sure that everything needed for LTO is built or around.

**Comment by dtarditi** [comment] 2019-09-02 19:46
@mgrang is working on this, so assigning this to him.

**Comment by dtarditi** [comment] 2024-09-01 17:38
This was implemented at Microsoft, but is not planned for the Checked C GitHub organization.

**Closed by dtarditi** 2024-09-01 17:38 UTC
Labels: feature, needs investigation
